version: '3.1'

services:

  protocol_db:
    image: postgres:13-alpine
#    healthcheck:
#      test: [ "CMD", "pg_isready", "-q", "-d", "protocoldb", "-U", "phaedra2" ]
#      timeout: 45s
#      interval: 10s
#      retries: 10
    restart: always
    hostname: protocol-db
    container_name: protocol-db
    networks:
      - phaedra2
    environment:
      - POSTGRES_DB=protocoldb
      - POSTGRES_USER=phaedra2
      - POSTGRES_PASSWORD=phaedra2
    volumes:
      - ./db/create-tables.sql:/opt/create-tables.sql
      - ./sh:/docker-entrypoint-initdb.d/
    ports:
      - 6543:5432

  protocol_service:
    image: pha2-protocol-service
    hostname: pha2-protocol-service
    container_name: pha2-protocol-service
    networks:
      - phaedra2
    ports:
      - 3030:3030
    depends_on:
      - protocol_db
    environment:
      - DB_URL=jdbc:postgresql://protocol-db:5432/protocoldb
      - DB_USERNAME=phaedra2
      - DB_PASSWORD=phaedra2

networks:
  phaedra2: