version: '3.5'

services:
  protocols_db:
    image: postgres:13-alpine
    restart: always
    hostname: protocols-db
    container_name: protocols-db
    networks:
      - private
    environment:
      - POSTGRES_DB=phaedra2
      - POSTGRES_USER=phaedra_usr
      - POSTGRES_PASSWORD=phaedra_usr
    volumes:
      - ./db/0-create-schema.sql:/opt/0-create-schema.sql
      - ./db/1-create-tables.sql:/opt/1-create-tables.sql
      - ./sh:/docker-entrypoint-initdb.d/
    ports:
      - 6543:5432
  protocol_service:
    image: phaedra2-protocolservice:0.0.1-SNAPSHOT
    hostname: phaedra2-protocolservice
    container_name: phaedra2-protocolservice
    networks:
      private:
      phaedra2:
        aliases:
          - phaedra2-protocolservice
    depends_on:
      - protocols_db
    environment:
      - DB_URL=jdbc:postgresql://protocols-db:5432/phaedra2?currentSchema=protocols
      - DB_USER=phaedra_usr
      - DB_PASSWORD=phaedra_usr
    expose:
      - 3001
    ports:
      - 3001:3001

networks:
  private:
    name: private
    external: false
  phaedra2:
    external:
      name: phaedra2