server:
  servlet:
    context-path: /phaedra/protocol-service
  port: 3001

spring:
  application:
    name: PHAEDRA-PROTOCOL-SERVICE
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/phaedra2?currentSchema=protocols
#    username: phaedra_usr
#    password: phaedra_usr
  jackson:
    serialization:
      indent_output: true

eureka:
  instance:
    appname: ${spring.application.name}

  client:
    service-url:
      defaultZone: ${SERVICE_REGISTRY}