server:
  servlet:
    context-path: /phaedra/protocol-service
  port: 3030

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/phaedra2?currentSchema=protocols
    username: phaedra_usr
    password: phaedra_usr
