server:
  servlet:
    context-path: /phaedra/protocol-service
  port: 3001

spring:
  cloud:
    kubernetes:
      enabled: false
  application:
    name: phaedra-protocol-service
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/phaedra2?currentSchema=protocols
#    username: phaedra_usr
#    password: phaedra_usr
  liquibase:
    enabled: false
  jackson:
    serialization:
      indent_output: true

eureka:
  client:
    enabled: true
