server:
  servlet:
    context-path: /phaedra/protocol-service
  port: 3001

spring:
  cloud:
    kubernetes:
      enabled: false
  application:
    name: phaedra-protocol-service
  liquibase:
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost
  jackson:
    serialization:
      indent_output: true

eureka:
  client:
    enabled: true
